# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PowerMonitorIOS' do

use_frameworks!

  pod 'SwiftyJSON', ">= 2.2"

	pod 'SwiftCharts', '~> 0.2'

	#pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'swift2.0'

end

