/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Session`;

DROP TABLE IF EXISTS `Reading`;

DROP TABLE IF EXISTS `SlaveModule`;

DROP TABLE IF EXISTS `InternalProfile`;

DROP TABLE IF EXISTS `DefaultProfile`;

DROP TABLE IF EXISTS `Alert_users`;

DROP TABLE IF EXISTS `Alert`;

DROP TABLE IF EXISTS `User`;

DROP TABLE IF EXISTS `TimeSlot`;

DROP TABLE IF EXISTS `Profile`;

DROP TABLE IF EXISTS `Unit`;

CREATE TABLE `Unit` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `symbol` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Profile` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `typeid` VARCHAR(255) NOT NULL,
  `polling` INT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `TimeSlot` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `beg_day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  `beg_minute` INT UNSIGNED NOT NULL,
  `end_day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  `end_minute` INT UNSIGNED NOT NULL,
  `profile` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `TimeSlot_profile_fk`
    FOREIGN KEY (`profile`)
    REFERENCES `Profile` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `User` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `surname` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `hash` BINARY(32) NOT NULL,
  `salt` BINARY(32) NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Alert` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `information_unit` BIGINT UNSIGNED NOT NULL,
  `information_value` DOUBLE NOT NULL,
  `profile` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `Alert_information_unit_fk`
    FOREIGN KEY (`information_unit`)
    REFERENCES `Unit` (`id`)
  */
  /*
  CONSTRAINT `Alert_profile_fk`
    FOREIGN KEY (`profile`)
    REFERENCES `Profile` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Alert_users` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `Alert_users_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Alert` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Alert_users_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `User` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Alert_users` (`object_id`);

CREATE TABLE `DefaultProfile` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  `name` TEXT NOT NULL,
  CONSTRAINT `DefaultProfile_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Profile` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `InternalProfile` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  CONSTRAINT `InternalProfile_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `Profile` (`id`)
    ON DELETE CASCADE)
 ENGINE=InnoDB;

CREATE TABLE `SlaveModule` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `serialNumber` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `defaultProfile` BIGINT UNSIGNED NULL,
  `internalProfile` BIGINT UNSIGNED NULL
  /*
  CONSTRAINT `SlaveModule_defaultProfile_fk`
    FOREIGN KEY (`defaultProfile`)
    REFERENCES `DefaultProfile` (`id`)
  */
  /*
  CONSTRAINT `SlaveModule_internalProfile_fk`
    FOREIGN KEY (`internalProfile`)
    REFERENCES `InternalProfile` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Reading` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `module` BIGINT UNSIGNED NOT NULL,
  `tp_point` BIGINT NOT NULL,
  `info_unit` BIGINT UNSIGNED NOT NULL,
  `info_value` DOUBLE NOT NULL
  /*
  CONSTRAINT `Reading_module_fk`
    FOREIGN KEY (`module`)
    REFERENCES `SlaveModule` (`id`)
  */
  /*
  CONSTRAINT `Reading_info_unit_fk`
    FOREIGN KEY (`info_unit`)
    REFERENCES `Unit` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Session` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user` BIGINT UNSIGNED NULL,
  `token` BINARY(32) NOT NULL
  /*
  CONSTRAINT `Session_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `User` (`id`)
  */)
 ENGINE=InnoDB;

